language: node_js
node_js:
  - "12.16.1"
branches:
  only:
    - master

addons:
  chrome: stable
  sonarcloud:
    organization: kiran3232
    token: $SONAR_TOKEN

cache:
  directories:
    - ./node_modules

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

install:
  - npm install

script:
  - ng test --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox --code-coverage
  - ng lint
  - ng build --prod

after_success:
  - sonar-scanner
  - firebase deploy --token $FIREBASE_TOKEN